import { Positions, TeamNames } from '../../enums';

export interface IPlayer {
  name: string;
  team: TeamNames;
  birthDate: string;
  price: number;
  selected: number;
  position: Positions;
  img: string;
  id: number;
}

const players: IPlayer[] = [
  {
    name: 'David Raya',
    team: TeamNames.BRE,
    birthDate: '15.09.1995',
    price: 4.8,
    selected: 15.6,
    position: Positions.GK,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p154561.png',
    id: 1,
  },
  {
    name: 'Nick Pope',
    team: TeamNames.NEW,
    birthDate: '19.04.1992',
    price: 5.4,
    selected: 20.9,
    position: Positions.GK,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p98747.png',
    id: 2,
  },
  {
    name: 'Kieran Trippier',
    team: TeamNames.NEW,
    birthDate: '19.09.1990',
    price: 6.0,
    selected: 64.9,
    position: Positions.DEF,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p77794.png',
    id: 3,
  },
  {
    name: 'Oleksandr Zinchenko',
    team: TeamNames.ARS,
    birthDate: '15.12.1996',
    price: 5.2,
    selected: 14.5,
    position: Positions.DEF,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p206325.png',
    id: 4,
  },
  {
    name: 'Pervis Estupiñán',
    team: TeamNames.BHA,
    birthDate: '21.01.1998',
    price: 4.8,
    selected: 11.7,
    position: Positions.DEF,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p204214.png',
    id: 5,
  },
  {
    name: 'Pedro Porro',
    team: TeamNames.TOT,
    birthDate: '13.09.1999',
    price: 4.8,
    selected: 0.3,
    position: Positions.DEF,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p441164.png',
    id: 6,
  },
  {
    name: 'Lewis Dunk',
    team: TeamNames.BHA,
    birthDate: '21.11.1991',
    price: 4.7,
    selected: 5.1,
    position: Positions.DEF,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p83299.png',
    id: 7,
  },
  {
    name: 'Kaoru Mitoma',
    team: TeamNames.BHA,
    birthDate: '20.05.1997',
    price: 5.5,
    selected: 22.4,
    position: Positions.MID,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p451340.png',
    id: 8,
  },
  {
    name: 'Gabriel Martinelli',
    team: TeamNames.ARS,
    birthDate: '18.06.2001',
    price: 6.6,
    selected: 37.5,
    position: Positions.MID,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p444145.png',
    id: 9,
  },
  {
    name: 'James Maddison',
    team: TeamNames.LEI,
    birthDate: '23.11.1996',
    price: 8.1,
    selected: 5.8,
    position: Positions.MID,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p172780.png',
    id: 10,
  },
  {
    name: 'Mohamed Salah',
    team: TeamNames.LIV,
    birthDate: '15.06.1992',
    price: 12.8,
    selected: 28.0,
    position: Positions.MID,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p118748.png',
    id: 11,
  },
  {
    name: 'Marcus Rashford',
    team: TeamNames.MUN,
    birthDate: '31.10.1997',
    price: 7.4,
    selected: 53.8,
    position: Positions.MID,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p176297.png',
    id: 12,
  },
  {
    name: 'Erling Haaland',
    team: TeamNames.MCI,
    birthDate: '21.07.2000',
    price: 12.2,
    selected: 82.3,
    position: Positions.FWD,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p223094.png',
    id: 13,
  },
  {
    name: 'Ivan Toney',
    team: TeamNames.BRE,
    birthDate: '16.03.1996',
    price: 7.8,
    selected: 39.6,
    position: Positions.FWD,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p144485.png',
    id: 14,
  },
  {
    name: 'Ollie Watkins',
    team: TeamNames.AVL,
    birthDate: '30.12.1995',
    price: 7.3,
    selected: 9.5,
    position: Positions.FWD,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p178301.png',
    id: 15,
  },
  {
    name: 'Harry Kane',
    team: TeamNames.TOT,
    birthDate: '28.07.1993',
    price: 11.7,
    selected: 38.5,
    position: Positions.FWD,
    img: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p78830.png',
    id: 16,
  },
];

export default players;
